# CI pipeline for nf-python

name: nf-python Release

on:
  push:
    tags:
      - 'v*'

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from MANIFEST.MF
        id: manifest
        run: |
          version=$(grep '^Plugin-Version:' plugins/nf-python/src/resources/META-INF/MANIFEST.MF | awk '{print $2}')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Extract version from git tag
        id: tag
        run: |
          tag_version=${GITHUB_REF##*/}
          tag_version=${tag_version#v}
          echo "version=$tag_version" >> $GITHUB_OUTPUT
      - name: Check versions match
        run: |
          if [ "${{ steps.manifest.outputs.version }}" != "${{ steps.tag.outputs.version }}" ]; then
            echo "MANIFEST.MF ${{ steps.manifest.outputs.version }} and git tag ${{ steps.tag.outputs.version }} do not match!"
            exit 1
          fi
          echo "All versions match: ${{ steps.manifest.outputs.version }}"

  build-plugin:
    needs: validate-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Nextflow plugin
        run: |
          make buildPlugins
      - name: Archive plugin zip
        uses: actions/upload-artifact@v4
        with:
          name: nf-python-plugin
          path: build/plugins/nf-python-*.zip
